services:
  gps_postgres:
    image: postgres:16
    container_name: gps_postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - gps_postgres_data:/var/lib/postgresql/data

  gps_redis:
    image: redis:7-alpine
    container_name: gps_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data

  app:
    profiles: ["prod"]
    build: .
    container_name: gps_backend
    depends_on:
      gps_postgres:
        condition: service_healthy
      gps_redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@gps_postgres:5432/${POSTGRES_DB}
      RUST_LOG: info
    ports:
      - "8000:8000"
    restart: unless-stopped

  dev:
    profiles: ["dev"]
    image: rust:latest
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - cargo_target:/app/target # persist compiled crates
      - cargo_registry:/usr/local/cargo/registry # optional: cache downloaded crates
    command: bash -c "apt-get update && apt-get install -y cmake build-essential clang pkg-config sqlite3 libsqlite3-dev pkg-config && rm -rf /var/lib/apt/lists/* && cargo run"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@gps_postgres:5432/${POSTGRES_DB}
      LIB:
      LIBPATH:
      VCPKG_ROOT:
      RUSTFLAGS:
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      gps_postgres:
        condition: service_healthy
      gps_redis:
        condition: service_healthy



volumes:
  gps_postgres_data:
  cargo_target:
  cargo_registry:
  redis_data:
